### ISSUE TITLE
Not Web Scale

### ISSUE THREAD

**Issue by cameronwebbable** [stakes/Snapbar#3]
Really should web scale.

Also, hey 👋. Wanted to take opportunity to troll a repo. (seriously though, I'm going to download. looks useful)

**Comment by drewbaumann** [comment]
HA. You troll you.

**Comment by stakes** [comment]
You found it you fix it

**Comment by stakes** [comment]
And 👋 I do like how an unanticipated side effect of my new interest in building menu bar apps is this little reunion of ours here

**Comment by cameronwebbable** [comment]
No. I judge from the peanut gallery. I demand all the free things because this an open source project. 

Plus I think @aharpole would be better at this.

**Comment by aharpole** [comment]
I'm generally pretty anti-menu bar app myself; I've got enough crap up there.

Also, [CleanShot X](https://cleanshot.com/) is pretty awesome.

**Comment by stakes** [comment]
Well you're going to hate whatever the next things I build are, then. In success you'll see me doing ALL my work from the menu bar exclusively

**Comment by stakes** [comment]
I legit bought this domain http://menubar.club/ that's how all in I am on the menu bar
